version: "3"

services:
  # API
  homeware-lan-back-api:
    image: ghcr.io/kikeelectronico/homewarelan-back
    hostname: backend
    environment:
      - REDIS_HOST=redis
      - MQTT_HOST=mosquitto
    expose:
      - "5001"
    depends_on:
      - redis
      - mosquitto

  # tasks
  homeware-lan-back-tasks:
    image: ghcr.io/kikeelectronico/homewarelan-back
    hostname: backend-tasks
    command: "python homewareTasks.py"
    environment:
      - REDIS_HOST=redis
      - MQTT_HOST=mosquitto
    depends_on:
      - redis
      - mosquitto

  # MQTT
  homeware-lan-back-mqtt:
    image: ghcr.io/kikeelectronico/homewarelan-back
    hostname: backend-mqtt
    command: "python homewareMQTT.py"
    environment:
      - REDIS_HOST=redis
      - MQTT_HOST=mosquitto
    depends_on:
      - redis
      - mosquitto

  # redis
  redis:
    image: redis:6.0
    hostname: redis
    expose:
      - "6379"
    volumes:
      - redis-data:/data

  # mosquitto
  mosquitto:
    image: eclipse-mosquitto:2.0
    hostname: mosquitto
    expose:
      - "1883"
    ports:
      - "1883:1883"
    volumes:
      - ./configuration_templates/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./configuration_templates/mosquitto_passwd:/mosquitto/config/passwd:ro
      - mosquitto-data:/mosquitto/data

  # nginx proxy for API & FE
  nginx:
    image: ghcr.io/kikeelectronico/homewarelan-nginx
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
    depends_on:
      - homeware-lan-back-api
      - nginx-proxy
    restart: always

  # nginx reverse proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  # certificate helper
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro


volumes:
  html:
  certs:
  vhostd:
  mosquitto-data:
  redis-data: