name: Testing backend
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - "back/**"
  pull_request:
    branches:
      - dev
    paths:
      - "back/**"

jobs:
  back:
    name: Test (red, py, moss)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [6]
        python-version: [3.7]
        mosquitto-version: [2.0]
    steps:
      - uses: actions/checkout@v1
      - name: Copy database template
        run: cp configuration_templates/template_homeware.json homeware.json
      - name: Create directories
        run: |
          mkdir logs
          mkdir files
      - name: Start Redis ${{ matrix.redis-version }}
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Start Mosquitto broker
        uses: Namoshek/mosquitto-github-action@v0.1.0
        with:
          version: ${{ matrix.mosquitto-version }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./back
      - name: Test
        uses: onichandame/python-test-action@master
        working-directory: ./back
